Remove hugrenv from the PATH on windows to avoid compiler conflicts

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -115,6 +115,22 @@ jobs:
         with:
           packages: "llvm"
 
+      - name: Remove hugrenv clang from PATH on Windows
+        # We add hugrenv to provide llvm tools bundled with selene.
+        # However, on Windows, this has the side effect of adding clang
+        # into the build environment in which e.g. stim is built, instead
+        # of the default compiler, and the build fails.
+        #
+        # TODO: investigate why that build fails.
+        #
+        # For now we just remove the bundled clang from the path.
+        if: ${{ startsWith(matrix.os, 'windows-') }}
+        shell: bash
+        run: |
+          set -euo pipefail
+          cleaned="$(printf '%s' "$PATH" | tr ';' '\n' | grep -vi '^C:\\hugrverse\\bin$' | paste -sd ';' -)"
+          echo "PATH=$cleaned" >> "$GITHUB_ENV"
+
       # --------------------------------
       # Build selene-sim wheel
       # --------------------------------
